<?php
    require_once('service/apply_data_operation/mainpage_require_all.php');
    require_once('service/user_operation/mainpage_require_all.php');
    require_once('service/dormitory_data_operation/mainpage_require_all.php');
    require_once('service/inform_operation/mainpage_require_all.php');
    require_once('service/border_operation/mainpage_require_all.php');
    require_once('service/init_sql.php');
    require_once('service/connect_db.php');
?>